### ISSUE TITLE
Green is too dark

### ISSUE THREAD

**Issue by Linuus** [whatyouhide/gotham-contrib#10]
Hi!

The green color seems to be a bit dark in iTerm2 sometimes. It makes it very hard to see text printed in green. See image below (there are a bunch of `create` statements in the left, dark area).

![skarmavbild 2015-02-20 kl 11 24 16](https://cloud.githubusercontent.com/assets/379823/6284686/1cd7a858-b8f3-11e4-80de-780c73578f30.png)

Hmm, it's harder to see on my Cinema Display than on the screen on my Macbook Air. But still, it's too dark to be useful :)

**Comment by whatyouhide** [comment]
Yes I'm aware of this, I still have to find some time to fix it :smile:. Sorry for the inconvenience!

**Comment by aminb** [comment]
@whatyouhide Any updates on this?

**Comment by artofhuman** [comment]
@whatyouhide ping

**Comment by whatyouhide** [comment]
Tattarataaa, finally got around and did this :) It's in `master` (`iterm2/Gotham.itermcolors`), @aminb @artofhuman @Linuus let me know what you think!

**Comment by aminb** [comment]
@whatyouhide I don't use iTerm2, can you please update the xresources folder, or tell us the changes in RGB?

**Comment by jalcine** [comment]
[**@whatyouhide**](https://github.com/whatyouhide) commented on [Sep 15, 2015, 9:10 AM EDT](https://github.com/whatyouhide/gotham-contrib/issues/10#issuecomment-140382447 "2015-09-15T13:10:08Z - Replied by Github Comment Enhancer"):
> Tattarataaa, finally got around and did this :) It's in `master` (`iterm2/Gotham.itermcolors`), [@aminb](https://github.com/aminb) [@artofhuman](https://github.com/artofhuman) [@Linuus](https://github.com/Linuus) let me know what you think!

In reference to [@aminb's comment](https://github.com/whatyouhide/gotham-contrib/issues/10#issuecomment-141865272), is there a way to fetch the `xresources` color?

**Comment by le0nik** [comment]
I can't use the Gotham.itermcolors theme in iterm2 (2.1.4).
I can import it, but when i try to use it, it colors dont' apply to the terminal at all.

Gotham-stable.itermcolors works though. Weird.

**Comment by gutierri** [comment]
@whatyouhide I have this problem in terminator :(. We can lighten a bit this color (?)

**Comment by whatyouhide** [comment]
Hey there folks, I practically have no time to work on this right now. Anyone willing to experiment with changing the color for one of the supported terminals and adding a bunch of screenshot here? We can discuss the new colour and port it to the other terminals. By "new colour" I mean re-using one of the other colours in place of the too dark green here. Wdyt?
