### ISSUE TITLE
textmate for sublime text color scheme?

### ISSUE THREAD

**Issue by levbrie** [whatyouhide/gotham-contrib#13]
I primarily use vim and love this theme but I would love to be able to unify all of my editors if possible.  Just wondering if it's in the works.

**Comment by whatyouhide** [comment]
@levbrie hey, thanks for the kind words! The answer is basically no, I'm not working on porting Gotham to any editor myself other than vim. That said, PRs are welcome and I'll leave this issue open and tagged as "help wanted" so maybe someone can contribute :)

**Comment by levbrie** [comment]
@whatyouhide awesome, thanks!  If I end up with a little time maybe I'll be able to work on porting it :)

**Comment by whatyouhide** [comment]
@levbrie it would be great, thanks :D

**Comment by whatyouhide** [comment]
@ljasinskipl implemented this and it was merged in #14!
