### ISSUE TITLE
terminal foreground too bright

### ISSUE THREAD

**Issue by alexanderjeurissen** [whatyouhide/gotham-contrib#17]
I love the gotham theme especially in vim, but the terminal theme isn't ideal as others have pointed out.

besides the dark green, I also find the foreground too bright It's okay for a short while but I'm sure it will irritate the eyes with prolonged use.

See the below two screenshots that demonstrates the difference between my modified foreground and the original one.

**gotham_stable:**
<img width="1196" alt="screen shot 2016-01-25 at 19 11 07" src="https://cloud.githubusercontent.com/assets/1220084/12559895/01949ca8-c398-11e5-9751-59db0f611767.png">

**my modification:**
<img width="1199" alt="screen shot 2016-01-25 at 19 10 55" src="https://cloud.githubusercontent.com/assets/1220084/12559894/01944636-c398-11e5-9c04-68ebe8b787d9.png">

seeing as the foreground is only used in the terminal theme, it won't impact the vim theme.

**Comment by whatyouhide** [comment]
I don't mind the change :), so if you're up for a PR that would be awesome! :heart_decoration:

**Comment by alexanderjeurissen** [comment]
Sure I'll create a PR, I'm not sure how changing the foreground in other terminal themes might affect the vim color scheme. So I'll create a PR for the iterm theme and we can later decide if this change can be applied to the other themes as well.

**Comment by whatyouhide** [comment]
Sounds like a good plan. We could even make a separate iTerm theme with this change (and maybe we could change the too dark colors in that theme), so we can experiment more freely. Wdyt?

**Comment by alexanderjeurissen** [comment]
@whatyouhide sounds good, the only thing i did was lower the brightness / lightness in the HSL for the foreground. The reverse (increasing the brightness) of the dark green should increase the readability.

**Comment by whatyouhide** [comment]
Sounds like a plan :)

**Comment by alexanderjeurissen** [comment]
I just checked and the new less bright foreground kind of ruins the vim theme...
I attached some screenshots to show this, with some vimscript shown as source.

<img width="1219" alt="screen shot 2016-01-26 at 12 37 35" src="https://cloud.githubusercontent.com/assets/1220084/12579706/3d872284-c42a-11e5-9cc6-c1d6311f0699.png">
<img width="1218" alt="screen shot 2016-01-26 at 12 38 06" src="https://cloud.githubusercontent.com/assets/1220084/12579705/3d839aa6-c42a-11e5-9b08-f2eecce933b6.png">

I'll have to tinker a bit with the color brightness to find the sweet spot.

**Comment by whatyouhide** [comment]
Whoops, yes the color is too dim/dark for the vim colorscheme. Go ahead and take your time :)

**Comment by alexanderjeurissen** [comment]
Ok i experimented a while with the colors and especially the brightness of the *Blue* and *White* colors and I think I found the sweetspot for both.

below are two screenshots one with the new gotham_ergo.itermcolors and one with the Gotham Stable. The difference is quite subtle but it's enough for making the blue more visible and enough brightness reduction of the foreground/white to make it easier on the eyes.

**Gotham stable:**
<img width="1280" alt="screen shot 2016-01-26 at 14 36 36" src="https://cloud.githubusercontent.com/assets/1220084/12582005/8a27df10-c43a-11e5-8d89-1c8e5016c50e.png">

**Gotham ergo:**
<img width="1280" alt="screen shot 2016-01-26 at 14 36 56" src="https://cloud.githubusercontent.com/assets/1220084/12582006/8a2c66f2-c43a-11e5-83f1-dd8c340c49a1.png">

a screenrecording hat shows the switching between the two colorschemes (easier to show the differences)
https://youtu.be/Mq9ftWeMpEY

**Comment by whatyouhide** [comment]
I like that, a lot! Please open a PR so that I can merge Gotham Ergo in. If we see people like it, we can make it the default gotham so that we don't have two of them lying around :)

**Comment by alexanderjeurissen** [comment]
Done. Glad you like it ;-)
