### ISSUE TITLE
Error when loading the Gotham theme for Sublime Text 3

### ISSUE THREAD

**Issue by andrewcodes** [whatyouhide/gotham-contrib#19]
Hi there, I'm getting this error when importing the theme for ST3:

<img width="532" alt="screen shot 2016-02-07 at 9 35 21 am" src="https://cloud.githubusercontent.com/assets/1760287/12873278/7640a7b4-cd7e-11e5-9315-22f832cebd4d.png">

Any ideas on what's going wrong on line 50? Thanks!

**Comment by whatyouhide** [comment]
I didn't create the Sublime port of the theme so I have no idea what's going on there :\ Let's ping @ljasinskipl and see if they know anything about this :)

**Comment by andrewcodes** [comment]
@whatyouhide @ljasinskipl this is working now - was an issue on my end. Thanks!
