### ISSUE TITLE
Tmux theme

### ISSUE THREAD

**Issue by shaneog** [whatyouhide/gotham-contrib#22]
I've built a Gotham theme for Tmux.
Should I submit it as a link in the README, or copy it to the repo here?

https://github.com/shaneog/tmux-colors-gotham

It requires the terminal theme for Gotham to be already set.

**Comment by whatyouhide** [comment]
Hey @shaneog, any of the two choices is fine: either submit as a link, or copy here, whatever you prefer :)

I'm gonna close this issue in favour of the upcoming PR then!

PS: sorry for the late response, was on vacation :)
