### ISSUE TITLE
Gotham theme for Intellij

### ISSUE THREAD

**Issue by MagisDing** [whatyouhide/gotham-contrib#29]
Hi, I really love your work and have switched themes to it for iTerm, terminal,emacs, but I am wondering if it is possible to use it for Intellij, I tried the one in the project, seems it didn't work. How to use it for Intellij?

**Comment by whatyouhide** [comment]
Hye @MagisDing, thanks for the report. @DreddyI is the author of that theme, any ideas @DreddyI?

**Comment by DreddyI** [comment]
Hi ther @MagisDing  @whatyouhide .
@MagisDing plz describe the problems that you've got?
Did you read the instruction?
https://github.com/whatyouhide/gotham-contrib#phpstormpycharm
May be some screenshots of problem?

**Comment by MagisDing** [comment]
@DreddyI @whatyouhide  Sorry for miss the messages and really appreciate for your replies.

I have followed the instructions and mainly used intelliJ for scala and javascript programming.
https://www.dropbox.com/s/kulqw7cxxwbhqbp/Screenshot%202017-03-08%2018.19.44.png?dl=0
https://www.dropbox.com/s/e081cx3mq0yknqc/Screenshot%202017-03-08%2018.20.11.png?dl=0

**Comment by DreddyI** [comment]
@MagisDing Hi there. the problem is that you put file into phpstorm\webstorm path
jetbrains have different paths for different IDEs.
if You're using last version of IDEA, than path for colors should be something like
for Community Edition:
~/Library/Preferences/IdeaIC2016.3/colors
for Ultimate Edition:
~/Library/Preferences/IntelliJIdea2016.3/colors

**Comment by MagisDing** [comment]
@DreddyI  Thanks, it works!

**Comment by MagisDing** [comment]
@DreddyI Hi， Ivan， seems it doesn't work in the official Ultimate Edition 2017.1.3.

**Comment by shaneog** [comment]
Confirmed that it doesn't work for the latest Ultimate 2018.2
