### ISSUE TITLE
Add Konsole support

### ISSUE THREAD

**Issue by gagbo** [whatyouhide/gotham-contrib#32]
I did not check that everything is right, but using [Terminal.sexy](terminal.sexy) I converted the .Xresources file to a Konsole colorscheme (to put in ~/.kde/share/apps/konsole/Gotham.colorscheme)

Note : Konsole should be restarted to see the colorscheme in the list of profiles

```
# --- special colors ---

[Background]
Color=10,15,20

[BackgroundIntense]
Color=10,15,20

[Foreground]
Color=152,209,206

[ForegroundIntense]
Color=152,209,206
Bold=true

# --- standard colors ---

[Color0]
Color=10,15,20

[Color0Intense]
Color=16,21,27

[Color1]
Color=195,48,39

[Color1Intense]
Color=210,105,57

[Color2]
Color=38,169,139

[Color2Intense]
Color=8,31,45

[Color3]
Color=237,181,75

[Color3Intense]
Color=36,83,97

[Color4]
Color=25,84,101

[Color4Intense]
Color=9,55,72

[Color5]
Color=78,81,101

[Color5Intense]
Color=136,139,165

[Color6]
Color=51,133,157

[Color6Intense]
Color=89,156,170

[Color7]
Color=152,209,206

[Color7Intense]
Color=211,235,233

# --- general options ---

[General]
Description=Gotham
Opacity=1
Wallpaper=
```

**Comment by whatyouhide** [comment]
> I did not check that everything is right

Please do then before we merge the PR. Also as stated in the README, can you please attach a screenshot of the result?

Thanks for contributing!

**Comment by whatyouhide** [comment]
Hey @gagbo, I will go ahead and close this issue so I can clean my pipeline a little bit but *please* feel free to reopen it if new info comes up or to open a PR :D.
