### ISSUE TITLE
gnome-terminal installer failed to get profile name

### ISSUE THREAD

**Issue by zack** [whatyouhide/gotham-contrib#34]
When executing both `install.sh` and `set_gotham.sh`, I've run into the following error on a brand new Ubuntu install, a brand new Manjaro install, and a ~4 month old Ubuntu install. Here is what's going on on Manjaro:

```
Please select a Gnome Terminal profile:

You have selected:

  Scheme:  gotham
Failed to get value for `/apps/gnome-terminal/profiles//visible_name':
Bad key or directory name: "/apps/gnome-terminal/profiles//visible_name":
Can't have two slashes '/' in a row
  Profile: is not a valid profile ()
```

In the most recent attempt, the profile has the name "gotham". This occurs in both bash and zsh.

Here are my relevant dconf installations:
```
→  gnome-terminal git:(master) pacman -Ss dconf          
extra/dconf 0.26.1-1 [installed]
    Configuration database system
extra/dconf-editor 3.26.2-1 (gnome-extra) [installed]
    dconf Editor
multilib/lib32-dconf 0.26.1-1 [installed]
    A low-level configuration system
```
As there haven't been any updates to the repository recently, I'm pretty confused considering that this is happening across multiple systems and is a new problem for me. Any help would be greatly appreciated.

Thanks!

**Comment by whatyouhide** [comment]
Hey @zack, I don't maintain the gnome-terminal theme. Could you help finding the PR that added support for it, and pinging the author of that PR here? Thanks! 💟

**Comment by zack** [comment]
Yeah sure! Looks like that would have been @metalelf0 ... in 2015! I can't help but think I'm doing something wrong here, but ... I can't figure out what it is. ):

**Comment by whatyouhide** [comment]
@t0phr would you mind sending up a PR? :)
