### ISSUE TITLE
PhpStorm/PyCharm instruction can be probably simplified

### ISSUE THREAD

**Issue by DamianSkrzypczak** [whatyouhide/gotham-contrib#37]
Currently, PhpStorm/PyCharm instruction tells user to move files to specific location for fonts, 
this can be simplified to just:

`"File > Settings > Editor > Color Scheme -> 
⚙ button (Scheme: [selection window] ⚙) -> Import Scheme"` 

Pycharm (I assume that other Jetbrain products as well) allow for import from `.icls` files, also it allows for easy scheme removal as well (option visible for external schema only). I checked `Gotham.icls` for both, Pycharm Community and Pro editions in newest versions and it works like charm :)

Thank you for Gotham colorscheme!

**Comment by whatyouhide** [comment]
Great suggestion @DamianSkrzypczak! Do you mind sending a PR please? :) Thank you in advance! 💟

**Comment by DamianSkrzypczak** [comment]
OK! :)

**Comment by DamianSkrzypczak** [comment]
PR sent :)

**Comment by whatyouhide** [comment]
Closing in favor of the PR. Thanks! 💟
